"""empty message

Revision ID: 3dc3717bbdb4
Revises: 39e75906422c
Create Date: 2021-06-10 20:31:50.864099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dc3717bbdb4'
down_revision = '39e75906422c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('hash_name', sa.String(length=25), nullable=False))
    op.create_unique_constraint(None, 'post', ['hash_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='unique')
    op.drop_column('post', 'hash_name')
    # ### end Alembic commands ###
